export const DEFAULT_EXERCISES = [
  // Chest
  { id: 'ex-001', name: 'Bench Press (Barbell)', muscleGroup: 'chest', equipment: 'barbell' },
  { id: 'ex-002', name: 'Incline Bench Press (Barbell)', muscleGroup: 'chest', equipment: 'barbell' },
  { id: 'ex-003', name: 'Decline Bench Press (Barbell)', muscleGroup: 'chest', equipment: 'barbell' },
  { id: 'ex-004', name: 'Bench Press (Dumbbell)', muscleGroup: 'chest', equipment: 'dumbbell' },
  { id: 'ex-005', name: 'Incline Press (Dumbbell)', muscleGroup: 'chest', equipment: 'dumbbell' },
  { id: 'ex-006', name: 'Dumbbell Fly', muscleGroup: 'chest', equipment: 'dumbbell' },
  { id: 'ex-007', name: 'Cable Fly', muscleGroup: 'chest', equipment: 'cable' },
  { id: 'ex-008', name: 'Push-Up', muscleGroup: 'chest', equipment: 'bodyweight' },
  { id: 'ex-009', name: 'Chest Press (Machine)', muscleGroup: 'chest', equipment: 'machine' },
  { id: 'ex-010', name: 'Pec Deck', muscleGroup: 'chest', equipment: 'machine' },

  // Back
  { id: 'ex-011', name: 'Deadlift (Barbell)', muscleGroup: 'back', equipment: 'barbell' },
  { id: 'ex-012', name: 'Bent-Over Row (Barbell)', muscleGroup: 'back', equipment: 'barbell' },
  { id: 'ex-013', name: 'Pull-Up', muscleGroup: 'back', equipment: 'bodyweight' },
  { id: 'ex-014', name: 'Chin-Up', muscleGroup: 'back', equipment: 'bodyweight' },
  { id: 'ex-015', name: 'Lat Pulldown', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex-016', name: 'Seated Cable Row', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex-017', name: 'Single-Arm Dumbbell Row', muscleGroup: 'back', equipment: 'dumbbell' },
  { id: 'ex-018', name: 'T-Bar Row', muscleGroup: 'back', equipment: 'barbell' },
  { id: 'ex-019', name: 'Face Pull', muscleGroup: 'back', equipment: 'cable' },
  { id: 'ex-020', name: 'Romanian Deadlift', muscleGroup: 'back', equipment: 'barbell' },

  // Legs
  { id: 'ex-021', name: 'Squat (Barbell)', muscleGroup: 'legs', equipment: 'barbell' },
  { id: 'ex-022', name: 'Front Squat', muscleGroup: 'legs', equipment: 'barbell' },
  { id: 'ex-023', name: 'Leg Press', muscleGroup: 'legs', equipment: 'machine' },
  { id: 'ex-024', name: 'Lunges (Bodyweight)', muscleGroup: 'legs', equipment: 'bodyweight' },
  { id: 'ex-025', name: 'Lunges (Dumbbell)', muscleGroup: 'legs', equipment: 'dumbbell' },
  { id: 'ex-026', name: 'Leg Extension', muscleGroup: 'legs', equipment: 'machine' },
  { id: 'ex-027', name: 'Leg Curl (Lying)', muscleGroup: 'legs', equipment: 'machine' },
  { id: 'ex-028', name: 'Leg Curl (Seated)', muscleGroup: 'legs', equipment: 'machine' },
  { id: 'ex-029', name: 'Calf Raise (Standing)', muscleGroup: 'legs', equipment: 'machine' },
  { id: 'ex-030', name: 'Calf Raise (Seated)', muscleGroup: 'legs', equipment: 'machine' },
  { id: 'ex-031', name: 'Hip Thrust (Barbell)', muscleGroup: 'legs', equipment: 'barbell' },
  { id: 'ex-032', name: 'Goblet Squat', muscleGroup: 'legs', equipment: 'kettlebell' },
  { id: 'ex-033', name: 'Bulgarian Split Squat', muscleGroup: 'legs', equipment: 'dumbbell' },
  { id: 'ex-034', name: 'Step-Ups', muscleGroup: 'legs', equipment: 'bodyweight' },

  // Shoulders
  { id: 'ex-035', name: 'Overhead Press (Barbell)', muscleGroup: 'shoulders', equipment: 'barbell' },
  { id: 'ex-036', name: 'Overhead Press (Dumbbell)', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { id: 'ex-037', name: 'Lateral Raise (Dumbbell)', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { id: 'ex-038', name: 'Lateral Raise (Cable)', muscleGroup: 'shoulders', equipment: 'cable' },
  { id: 'ex-039', name: 'Front Raise (Dumbbell)', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { id: 'ex-040', name: 'Rear Delt Fly (Dumbbell)', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { id: 'ex-041', name: 'Upright Row (Barbell)', muscleGroup: 'shoulders', equipment: 'barbell' },
  { id: 'ex-042', name: 'Arnold Press', muscleGroup: 'shoulders', equipment: 'dumbbell' },
  { id: 'ex-043', name: 'Shoulder Press (Machine)', muscleGroup: 'shoulders', equipment: 'machine' },

  // Arms
  { id: 'ex-044', name: 'Bicep Curl (Barbell)', muscleGroup: 'arms', equipment: 'barbell' },
  { id: 'ex-045', name: 'Bicep Curl (Dumbbell)', muscleGroup: 'arms', equipment: 'dumbbell' },
  { id: 'ex-046', name: 'Hammer Curl', muscleGroup: 'arms', equipment: 'dumbbell' },
  { id: 'ex-047', name: 'Preacher Curl', muscleGroup: 'arms', equipment: 'barbell' },
  { id: 'ex-048', name: 'Cable Bicep Curl', muscleGroup: 'arms', equipment: 'cable' },
  { id: 'ex-049', name: 'Tricep Pushdown (Cable)', muscleGroup: 'arms', equipment: 'cable' },
  { id: 'ex-050', name: 'Skull Crusher', muscleGroup: 'arms', equipment: 'barbell' },
  { id: 'ex-051', name: 'Tricep Dip', muscleGroup: 'arms', equipment: 'bodyweight' },
  { id: 'ex-052', name: 'Overhead Tricep Extension', muscleGroup: 'arms', equipment: 'dumbbell' },
  { id: 'ex-053', name: 'Close-Grip Bench Press', muscleGroup: 'arms', equipment: 'barbell' },

  // Core
  { id: 'ex-054', name: 'Plank', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex-055', name: 'Crunch', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex-056', name: 'Sit-Up', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex-057', name: 'Leg Raise (Hanging)', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex-058', name: 'Russian Twist', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex-059', name: 'Cable Crunch', muscleGroup: 'core', equipment: 'cable' },
  { id: 'ex-060', name: 'Ab Rollout', muscleGroup: 'core', equipment: 'bodyweight' },
  { id: 'ex-061', name: 'Mountain Climber', muscleGroup: 'core', equipment: 'bodyweight' },

  // Cardio
  { id: 'ex-062', name: 'Treadmill Run', muscleGroup: 'cardio', equipment: 'machine' },
  { id: 'ex-063', name: 'Stationary Bike', muscleGroup: 'cardio', equipment: 'machine' },
  { id: 'ex-064', name: 'Rowing Machine', muscleGroup: 'cardio', equipment: 'machine' },
  { id: 'ex-065', name: 'Stair Climber', muscleGroup: 'cardio', equipment: 'machine' },
  { id: 'ex-066', name: 'Jump Rope', muscleGroup: 'cardio', equipment: 'bodyweight' },
  { id: 'ex-067', name: 'Burpee', muscleGroup: 'cardio', equipment: 'bodyweight' },
  { id: 'ex-068', name: 'Box Jump', muscleGroup: 'cardio', equipment: 'bodyweight' },
  { id: 'ex-069', name: 'Kettlebell Swing', muscleGroup: 'cardio', equipment: 'kettlebell' },
  { id: 'ex-070', name: 'Battle Ropes', muscleGroup: 'cardio', equipment: 'machine' },
];
