import { StyleSheet } from 'react-native';
import { Colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  title: { fontSize: 17, fontWeight: '600', color: Colors.text },
  saveText: { fontSize: 16, fontWeight: '600', color: Colors.primary },
  nameSection: { padding: 16 },
  nameInput: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 16,
    fontWeight: '500',
    color: Colors.text,
  },
  totalsBar: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
    alignItems: 'center',
  },
  totalsCal: { fontSize: 14, fontWeight: '700', color: Colors.text },
  totalsMacro: { fontSize: 12, color: Colors.textMuted },
  list: { paddingHorizontal: 16, paddingBottom: 40 },
  emptyItems: { alignItems: 'center', paddingTop: 32 },
  emptyText: { color: Colors.textMuted, fontSize: 14 },
  draftItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 12,
  },
  draftLeft: { flex: 1 },
  draftName: { fontSize: 14, fontWeight: '500', color: Colors.text },
  draftCal: { fontSize: 12, color: Colors.textMuted, marginTop: 2 },
  draftControls: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  stepBtn: {
    width: 30,
    height: 30,
    backgroundColor: Colors.surface,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  servingsText: { fontSize: 15, fontWeight: '600', color: Colors.text, minWidth: 28, textAlign: 'center' },
  removeBtn: { padding: 4, marginLeft: 4 },
  sep: { height: 1, backgroundColor: Colors.border },
  addFoodBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 4,
  },
  addFoodText: { fontSize: 15, fontWeight: '500', color: Colors.primary },
  modal: { flex: 1, backgroundColor: Colors.background },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  modalSearch: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 6,
  },
  modalInput: { flex: 1, fontSize: 15, color: Colors.text, padding: 0 },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  searchName: { fontSize: 15, fontWeight: '500', color: Colors.text },
  searchBrand: { fontSize: 12, color: Colors.textMuted },
  searchCal: { fontSize: 14, fontWeight: '600', color: Colors.text },
});
