import { StyleSheet } from 'react-native';
import { Colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 4,
  },
  topBarTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: Colors.text,
    letterSpacing: -0.5,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 12,
    paddingBottom: 8,
    gap: 20,
  },
  arrow: { padding: 4 },
  dateLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.text,
    minWidth: 100,
    textAlign: 'center',
  },
  loader: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  scroll: { flex: 1 },
  scrollContent: { paddingTop: 8 },
  summaryCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 16,
    gap: 16,
  },
  ringRow: { flexDirection: 'row', alignItems: 'center', gap: 20 },
  goalStack: { flex: 1, gap: 6 },
  goalTitle: { fontSize: 12, color: Colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.5 },
  goalVal: { fontSize: 20, fontWeight: '700', color: Colors.text, marginBottom: 4 },
  goalStat: { flexDirection: 'row', justifyContent: 'space-between' },
  statLabel: { fontSize: 13, color: Colors.textMuted },
  statVal: { fontSize: 13, fontWeight: '600', color: Colors.text },
  macroSection: { flexDirection: 'row', gap: 12 },
  addMealBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    borderStyle: 'dashed',
    marginBottom: 12,
  },
  addMealText: { fontSize: 14, fontWeight: '500', color: Colors.primary },
  bottomPad: { height: 100 },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: Colors.overlay,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  modalBox: {
    width: '100%',
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 20,
    gap: 16,
  },
  modalTitle: { fontSize: 17, fontWeight: '700', color: Colors.text },
  modalInput: {
    backgroundColor: Colors.surface2,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: Colors.text,
  },
  modalBtns: { flexDirection: 'row', gap: 10 },
  modalCancel: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: Colors.surface2,
    alignItems: 'center',
  },
  modalCancelText: { fontSize: 15, color: Colors.textSecondary, fontWeight: '500' },
  modalConfirm: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: Colors.primary,
    alignItems: 'center',
  },
  modalConfirmDisabled: { opacity: 0.4 },
  modalConfirmText: { fontSize: 15, color: Colors.textInverse, fontWeight: '700' },
});

export const macroBarStyles = StyleSheet.create({
  wrap: { flex: 1, gap: 4 },
  labels: { flexDirection: 'row', justifyContent: 'space-between' },
  label: { fontSize: 12, color: Colors.textMuted },
  val: { fontSize: 12, fontWeight: '600', color: Colors.text },
  goal: { fontWeight: '400', color: Colors.textMuted },
});

export const waterStyles = StyleSheet.create({
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 14,
    gap: 8,
  },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  title: { fontSize: 14, fontWeight: '600', color: Colors.text },
  amount: { fontSize: 13 },
  current: { color: '#4FC3F7', fontWeight: '700' },
  goal: { color: Colors.textMuted, fontWeight: '400' },
  bar: {
    height: 6,
    backgroundColor: Colors.surface2,
    borderRadius: 3,
    overflow: 'hidden',
  },
  fill: {
    height: 6,
    backgroundColor: '#4FC3F7',
    borderRadius: 3,
  },
  remaining: { fontSize: 11, color: Colors.textMuted },
  quickAdd: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  pill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: Colors.surface2,
  },
  pillCustom: { paddingHorizontal: 10 },
  pillText: { fontSize: 12, fontWeight: '600', color: '#4FC3F7' },
});
