import { StyleSheet } from 'react-native';
import { Colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  title: { fontSize: 17, fontWeight: '600', color: Colors.text },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, padding: 24 },
  emptyTitle: { fontSize: 18, fontWeight: '600', color: Colors.text },
  emptyDesc: { fontSize: 14, color: Colors.textMuted, textAlign: 'center' },
  createBtn: { backgroundColor: Colors.primaryMuted, paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12 },
  createBtnText: { color: Colors.primary, fontWeight: '600', fontSize: 15 },
  list: { padding: 16 },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    gap: 6,
  },
  cardHeader: { gap: 4 },
  cardTitleRow: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
  cardName: { fontSize: 16, fontWeight: '700', color: Colors.text },
  cardItems: { fontSize: 12, color: Colors.textMuted },
  cardMacros: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  cardCal: { fontSize: 14, fontWeight: '600', color: Colors.text },
  macroChip: { fontSize: 12, color: Colors.textMuted },
  ingredient: { fontSize: 13, color: Colors.textSecondary, paddingLeft: 4 },
  moreItems: { fontSize: 12, color: Colors.textMuted, paddingLeft: 4 },
  cardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  deleteAction: { padding: 6 },
  logBtn: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 9,
    borderRadius: 10,
    minWidth: 90,
    alignItems: 'center',
  },
  logBtnDisabled: { opacity: 0.6 },
  logBtnText: { color: Colors.textInverse, fontWeight: '600', fontSize: 14 },
});
