import { StyleSheet } from 'react-native';
import { Colors } from '../constants/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  title: { fontSize: 28, fontWeight: '700', color: Colors.text, letterSpacing: -0.5 },
  logBtn: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  logBtnText: { color: Colors.textInverse, fontWeight: '600', fontSize: 14 },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 40 },

  // Stats card
  statsCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    flexDirection: 'row',
  },
  statItem: { flex: 1, alignItems: 'center', gap: 4 },
  statVal: { fontSize: 20, fontWeight: '700', color: Colors.text },
  statLabel: { fontSize: 11, color: Colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.4 },
  statDivider: { width: 1, backgroundColor: Colors.border, marginVertical: 4 },

  // Chart card
  chartCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingTop: 16,
    overflow: 'hidden',
  },
  chartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  chartTitle: { fontSize: 15, fontWeight: '600', color: Colors.text },
  rangeToggle: {
    flexDirection: 'row',
    backgroundColor: Colors.surface2,
    borderRadius: 8,
    padding: 2,
    gap: 2,
  },
  rangeBtn: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  rangeBtnActive: { backgroundColor: Colors.surface3 },
  rangeBtnText: { fontSize: 12, color: Colors.textMuted, fontWeight: '500' },
  rangeBtnTextActive: { color: Colors.text },

  // Entry list
  sectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingHorizontal: 16,
    marginBottom: 8,
    marginTop: 4,
  },
  entryCard: {
    backgroundColor: Colors.surface,
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  entryLeft: { flex: 1, gap: 2 },
  entryDate: { fontSize: 15, fontWeight: '500', color: Colors.text },
  entryNotes: { fontSize: 12, color: Colors.textMuted },
  entryWeight: { fontSize: 22, fontWeight: '700', color: Colors.primary },
  entryUnit: { fontSize: 13, color: Colors.textMuted, fontWeight: '400' },
  entryDelete: { padding: 8 },

  // Empty state
  empty: { alignItems: 'center', justifyContent: 'center', paddingTop: 80, gap: 12 },
  emptyText: { fontSize: 16, fontWeight: '600', color: Colors.text },
  emptyDesc: { fontSize: 14, color: Colors.textMuted, textAlign: 'center', paddingHorizontal: 32 },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: Colors.overlay,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    gap: 16,
  },
  modalHandle: {
    width: 36,
    height: 4,
    backgroundColor: Colors.border,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 4,
  },
  modalTitle: { fontSize: 19, fontWeight: '700', color: Colors.text },
  weightRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  weightInput: {
    flex: 1,
    backgroundColor: Colors.surface2,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 28,
    fontWeight: '700',
    color: Colors.text,
    textAlign: 'center',
  },
  unitToggle: {
    backgroundColor: Colors.surface2,
    borderRadius: 10,
    padding: 3,
    gap: 2,
  },
  unitBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8 },
  unitBtnActive: { backgroundColor: Colors.primary },
  unitBtnText: { fontSize: 14, fontWeight: '600', color: Colors.textMuted },
  unitBtnTextActive: { color: Colors.textInverse },
  notesInput: {
    backgroundColor: Colors.surface2,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: Colors.text,
    minHeight: 60,
  },
  saveBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnDisabled: { opacity: 0.5 },
  saveBtnText: { color: Colors.textInverse, fontSize: 16, fontWeight: '700' },
  modalCancel: { alignItems: 'center', paddingVertical: 8 },
  modalCancelText: { fontSize: 15, color: Colors.textMuted },
});
